/**:
  ros__parameters:
    circumscribed_radius: 0.113
    inscribed_radius: 0.113
    observation_sources: scan
    robot_base_frame: $(arg frame)base_footprint
    robot_radius: 0.113
    scan:
      clearing: true
      data_type: LaserScan
      marking: true
      sensor_frame: $(arg frame)base_scan
      topic: $(arg namespace)/scan
