/**:
  ros__parameters:
    ekf_localization:
      base_link_frame: base_link
      frequency: 50
      imu0: /imu/data
      imu0_config:
      - false
      - false
      - false
      - false
      - false
      - false
      - false
      - false
      - false
      - false
      - false
      - true
      - true
      - true
      - false
      imu0_differential: false
      odom0: /ridgeback_velocity_controller/odom
      odom0_config:
      - false
      - false
      - false
      - false
      - false
      - false
      - true
      - true
      - false
      - false
      - false
      - true
      - false
      - false
      - false
      odom0_differential: false
      odom_frame: odom
      two_d_mode: true
      world_frame: odom
    ridgeback_joint_publisher:
      publish_rate: 50
      type: joint_state_controller/JointStateController
    ridgeback_velocity_controller:
      angular:
        z:
          has_acceleration_limits: true
          has_velocity_limits: true
          max_acceleration: 1.0
          max_velocity: 2.0
      back_left_wheel_joint: rear_left_wheel
      back_right_wheel_joint: rear_right_wheel
      cmd_vel_timeout: 0.25
      enable_odom_tf: false
      front_left_wheel_joint: front_left_wheel
      front_right_wheel_joint: front_right_wheel
      linear:
        x:
          has_acceleration_limits: true
          has_velocity_limits: true
          max_acceleration: 2.5
          max_velocity: 1.1
        y:
          has_acceleration_limits: true
          has_velocity_limits: true
          max_acceleration: 2.5
          max_velocity: 1.1
      pose_covariance_diagonal:
      - 0.001
      - 0.001
      - 1000000.0
      - 1000000.0
      - 1000000.0
      - 0.03
      publish_rate: 50
      twist_covariance_diagonal:
      - 0.001
      - 0.001
      - 0.001
      - 1000000.0
      - 1000000.0
      - 0.03
      type: mecanum_drive_controller/MecanumDriveController
      wheel_radius_multiplier: 1.0
      wheel_separation_multiplier: 1.0
      wheel_separation_x: 0.638
      wheel_separation_y: 0.551
