/**:
  ros__parameters:
    bodies:
    - color:
      - 1
      - 1
      - 1
      - 0.75
      footprints:
      - center:
        - -1
        - 0.0
        density: 1
        radius: 0.5
        type: circle
      name: waker
      pose:
      - 0
      - 0
      - 0
      type: dynamic
    plugins:
    - body: waker
      delta:
      - 5
      - 3
      - 3.141592
      duration: 30.0
      easing: quadraticInOut
      mode: yoyo
      name: Tween
      type: Tween
    - name: tf_publisher
      publish_tf_world: false
      type: ModelTfPublisher
