/**:
  ros__parameters:
    baudrate: 38400
    devicedriver: ms-35
    devicestring: /dev/ttyLED
    invert_output: false
    marker_frame: base_link
    pubmarker: false
    startup_color:
    - 0.0
    - 1.0
    - 0.0
    - 1.0
    startup_mode: Static
