/**:
  ros__parameters:
    bodies:
    - color:
      - 0.8
      - 0.2
      - 0
      - 1.0
      footprints:
      - collision: false
        density: 1
        layers:
        - static
        points:
        - - -0.4
          - 0.3
        - - 0.4
          - 0.3
        - - 0.4
          - -0.3
        - - -0.4
          - -0.3
        type: polygon
      name: base
