/**:
  ros__parameters:
    DwaLocalPlannerROS:
      acc_lim_th: 20.0
      acc_lim_x: 10.0
      angular_sim_granularity: 0.02
      controller_frequency: 20.0
      escape_reset_dist: 0.1
      escape_reset_theta: 0.1
      forward_point_distance: 0.355
      goal_distance_bias: 24.0
      max_rot_vel: 1.57
      max_vel_trans: 2.0
      max_vel_x: 2.0
      max_vel_y: 0.0
      min_rot_vel: 0.14
      min_vel_x: -0.5
      min_vel_y: 0.0
      occdist_scale: 1
      oscillation_reset_dist: 1
      path_distance_bias: 94.0
      sim_granularity: 0.02
      sim_time: 2.0
      theta_stopped_vel: 2.0
      trans_stopped_vel: 0.1
      vx_samples: 6
