/**:
  ros__parameters:
    MpcLocalPlannerROS:
      footprint_model:
        type: polygon
        vertices:
        - - -0.21
          - -0.165
        - - -0.21
          - 0.165
        - - 0.21
          - 0.165
        - - 0.21
          - -0.165
      grid:
        type: fd_grid
        variable_grid:
          enable: false
      planning:
        objective:
          type: quadratic_form
        terminal_constraint:
          type: none
        terminal_cost:
          type: quadratic
      robot:
        type: unicycle
        unicycle:
          acc_lim_theta: 20.0
          acc_lim_x: 10.0
          dec_lim_x: 10.0
          max_vel_theta: 1.57
          max_vel_x: 2.0
          max_vel_x_backwards: 0.5
      solver:
        lsq_lm:
          iterations: 10
        type: ipopt
