/**:
  ros__parameters:
    TebLocalPlannerROS:
      acc_lim_theta: 0.5
      acc_lim_x: 0.5
      allow_init_with_backwards_motion: false
      exact_arc_length: false
      footprint_model:
        type: point
      global_plan_prune_distance: 1
      global_plan_viapoint_sep: -1
      max_samples: 500
      max_vel_theta: 0.3
      max_vel_x: 0.4
      max_vel_x_backwards: 0.2
      max_vel_y: 0.0
      min_turning_radius: 0.0
      odom_topic: odom
      publish_feedback: false
