/**:
  ros__parameters:
    nodes:
      b_caster_rotation_joint:
        dcf_overlay:
          607C: '11179.7'
      fl_caster_rotation_joint:
        dcf_overlay:
          607C: '132218.1'
      fr_caster_rotation_joint:
        dcf_overlay:
          607C: '-108902.4'
