/**:
  ros__parameters:
    jackal_joint_publisher:
      publish_rate: 50
      type: joint_state_controller/JointStateController
    jackal_velocity_controller:
      angular:
        z:
          has_acceleration_limits: true
          has_velocity_limits: true
          max_acceleration: 25.0
          max_velocity: 4.0
      base_frame_id: base_link
      cmd_vel_timeout: 0.25
      enable_odom_tf: false
      k_l: 0.1
      k_r: 0.1
      left_wheel:
      - front_left_wheel
      - rear_left_wheel
      linear:
        x:
          has_acceleration_limits: true
          has_velocity_limits: true
          max_acceleration: 20.0
          max_velocity: 2.0
      odom_frame_id: odom
      pose_covariance_diagonal:
      - 0.001
      - 0.001
      - 1000000.0
      - 1000000.0
      - 1000000.0
      - 0.03
      publish_rate: 50
      right_wheel:
      - front_right_wheel
      - rear_right_wheel
      twist_covariance_diagonal:
      - 0.001
      - 0.001
      - 0.001
      - 1000000.0
      - 1000000.0
      - 0.03
      type: diff_drive_controller/DiffDriveController
      wheel_radius_multiplier: 1.0
      wheel_separation_multiplier: 1.5
