/**:
  ros__parameters:
    actions:
      continuous:
        angular_range:
        - -4.0
        - 4.0
        linear_range:
        - -2.0
        - 2.0
      discrete:
      - angular: 0.0
        linear: 0.3
        name: move_forward
      - angular: 0.0
        linear: -0.15
        name: move_backward
      - angular: 0.35
        linear: 0.15
        name: turn_left
      - angular: -0.35
        linear: 0.15
        name: turn_right
      - angular: 0.75
        linear: 0.0
        name: turn_strong_left
      - angular: -0.75
        linear: 0.0
        name: turn_strong_right
      - angular: 0.0
        linear: 0.0
        name: stop
    is_holonomic: false
    laser:
      angle:
        increment: 0.00654497222
        max: 2.35619
        min: -2.35619
      num_beams: 720
      range: 30.0
      update_rate: 10
    robot_base_frame: base_link
    robot_model: jackal
    robot_radius: 0.267
    robot_sensor_frame: front_laser
