/**:
  ros__parameters:
    circumscribed_radius: 0.267
    footprint:
    - - -0.105
      - -0.105
    - - -0.105
      - 0.105
    - - 0.041
      - 0.105
    - - 0.041
      - -0.105
    inscribed_radius: 0.267
    observation_sources: scan
    robot_base_frame: $(arg frame)base_footprint
    robot_radius: 0.105
    scan:
      clearing: true
      data_type: LaserScan
      marking: true
      sensor_frame: $(arg frame)base_scan
      topic: $(arg namespace)/scan
