/**:
  ros__parameters:
    footprint:
    - - 0.513
      - 0.364
    - - 0.513
      - -0.364
    - - -0.513
      - -0.364
    - - -0.513
      - 0.364
    footprint_padding: 0.01
    inscribed_radius: 0.629
    observation_sources: scan
    robot_base_frame: $(arg frame)base_link
    robot_radius: 0.629
    scan:
      clearing: true
      data_type: LaserScan
      inf_is_valid: true
      marking: true
      max_obstacle_height: 2.0
      min_obstacle_height: 0.0
      sensor_frame: $(arg frame)scan_link
      topic: $(arg namespace)/scan
