/**:
  ros__parameters:
    bodies:
    - color:
      - 1
      - 1
      - 1
      - 0.75
      footprints:
      - density: 100
        points:
        - - -1.03
          - -0.337
        - - 0.07983
          - -0.337
        - - 0.3
          - -.16111
        - - 0.3
          - 0.16111
        - - 0.07983
          - 0.337
        - - -1.03
          - 0.337
        type: polygon
      name: base
      type: dynamic
    - color:
      - 1
      - 1
      - 1
      - 0.75
      footprints:
      - density: 1.0
        points:
        - - 0.0875
          - -0.025
        - - 0.0875
          - 0.025
        - - -0.0875
          - 0.025
        - - -0.0875
          - -0.025
        type: polygon
      name: front_wheel
    - color:
      - 1
      - 1
      - 1
      - 0.75
      footprints:
      - density: 1.0
        points:
        - - 0.0875
          - -0.0255
        - - 0.0875
          - 0.0255
        - - -0.0875
          - 0.0255
        - - -0.0875
          - -0.0255
        type: polygon
      name: rear_left_wheel
    - color:
      - 1
      - 1
      - 1
      - 0.75
      footprints:
      - density: 1.0
        points:
        - - 0.0875
          - -0.0255
        - - 0.0875
          - 0.0255
        - - -0.0875
          - 0.0255
        - - -0.0875
          - -0.0255
        type: polygon
      name: rear_right_wheel
    joints:
    - bodies:
      - anchor:
        - 0
        - 0
        name: front_wheel
      - anchor:
        - 0
        - 0
        name: base
      name: front_wheel_revolute
      type: revolute
    - bodies:
      - anchor:
        - 0
        - 0
        name: rear_left_wheel
      - anchor:
        - -0.83
        - 0.29
        name: base
      name: rear_right_wheel_weld
      type: weld
    - bodies:
      - anchor:
        - 0
        - 0
        name: rear_right_wheel
      - anchor:
        - -0.83
        - -0.29
        name: base
      name: rear_left_wheel_weld
      type: weld
    plugins:
    - name: tf_publisher
      publish_tf_world: true
      type: ModelTfPublisher
    - body: base
      front_wheel_joint: front_wheel_revolute
      name: cleaner_drive
      odom_frame_id: map
      rear_left_wheel_joint: rear_left_wheel_weld
      rear_right_wheel_joint: rear_right_wheel_weld
      type: TricycleDrive
    - angle:
        increment: 0.004363323129985824
        max: 2.356194490192345
        min: -2.356194490192345
      body: base
      broadcast_tf: true
      frame: laser_front
      name: laser_front
      noise_std_dev: 0.05
      origin:
      - 0.28
      - 0
      - 0
      range: 20
      topic: scan
      type: Laser
      update_rate: 40
    - name: simple
      type: Simple
    - body: base
      name: constant
      omega: 0.3
      type: ConstVelocity
      vel_x: 0
      vel_y: 0
