/**:
  ros__parameters:
    TrajectoryPlannerROS:
      acc_lim_theta: 0.3
      acc_lim_x: 0.5
      angular_sim_granularity: 0.02
      controller_frequency: 5.0
      dwa: true
      escape_reset_dist: 0.1
      escape_reset_theta: 0.1
      escape_vel: -0.5
      gdist_scale: 1.0
      heading_lookahead: 0.325
      heading_scoring: false
      heading_scoring_timestep: 0.8
      holonomic_robot: false
      latch_xy_goal_tolerance: false
      max_vel_theta: 0.4
      max_vel_x: 0.5
      meter_scoring: true
      min_in_place_vel_theta: 0.08
      min_vel_theta: -0.4
      min_vel_x: 0.1
      occdist_scale: 0.1
      oscillation_reset_dist: 0.05
      pdist_scale: 0.75
      publish_cost_grid_pc: true
      sim_granularity: 0.02
      sim_time: 2.0
      simple_attractor: false
      vtheta_samples: 20
      vx_samples: 6
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.15
