/**:
  ros__parameters:
    GlobalPlanner:
      allow_unknown: true
      default_tolerance: 0.01
      old_navfn_behavior: false
      orientation_mode: 2
      orientation_window_size: 2
      use_dijkstra: true
      use_grid_path: false
      use_quadratic: true
      visualize_potential: true
    conservative_reset_dist: 3.0
    controller_frequency: 5.0
    controller_patience: 15.0
    oscillation_distance: 0.2
    oscillation_timeout: 10.0
    planner_frequency: 5.0
    recovery_behavior_enabled: false
    recovery_behaviour_enabled: false
    robot_frame: $(arg frame)base_link
