/**:
  ros__parameters:
    MpcLocalPlannerROS:
      footprint_model:
        type: polygon
        vertices:
        - - 0.513
          - 0.364
        - - 0.513
          - -0.364
        - - -0.513
          - -0.364
        - - -0.513
          - 0.364
      grid:
        type: fd_grid
        variable_grid:
          enable: false
      planning:
        objective:
          type: quadratic_form
        terminal_constraint:
          type: none
        terminal_cost:
          type: quadratic
      robot:
        type: unicycle
        unicycle:
          acc_lim_theta: 0.3
          acc_lim_x: 0.5
          dec_lim_x: 0.5
          max_vel_theta: 0.4
          max_vel_x: 0.5
          max_vel_x_backwards: 0.5
      solver:
        lsq_lm:
          iterations: 10
        type: ipopt
