/**:
  ros__parameters:
    TebLocalPlannerROS:
      acc_lim_theta: 0.3
      acc_lim_x: 0.5
      dt_ref: 0.5
      footprint_model:
        type: polygon
        vertices:
        - - 0.513
          - 0.364
        - - 0.513
          - -0.364
        - - -0.513
          - -0.364
        - - -0.513
          - 0.364
      max_vel_theta: 0.4
      max_vel_x: 0.5
      max_vel_x_backwards: 0.5
      max_vel_y: 0.0
      min_turning_radius: 0.0
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.15
