/**:
  ros__parameters:
    camera_matrix:
      cols: 3
      data:
      - 2478.10117
      - 0.0
      - 676.94299
      - 0.0
      - 2480.12385
      - 500.31739
      - 0.0
      - 0.0
      - 1.0
      rows: 3
    camera_name: left
    distortion_coefficients:
      cols: 5
      data:
      - -0.1102
      - 0.13941
      - -0.00081
      - -0.00164
      - 0.0
      rows: 1
    distortion_model: plumb_bob
    frame_id: /head_color_camera_l_link
    image_height: 1024
    image_width: 1360
    projection_matrix:
      cols: 4
      data:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      rows: 3
    rectification_matrix:
      cols: 3
      data:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      rows: 3
