/**:
  ros__parameters:
    camera_matrix:
      cols: 3
      data:
      - 1680.42785
      - 0.0
      - 519.168401
      - 0.0
      - 1680.703878
      - 489.716604
      - 0.0
      - 0.0
      - 1.0
      rows: 3
    camera_name: right
    distortion_coefficients:
      cols: 5
      data:
      - -0.267916
      - 0.275592
      - 0.00028
      - 0.000391
      - 0.0
      rows: 1
    distortion_model: plumb_bob
    frame_id: /head_color_camera_r_link
    image_height: 1024
    image_width: 1024
    projection_matrix:
      cols: 4
      data:
      - 1680.42785
      - 0.0
      - 519.168401
      - 0.0
      - 0.0
      - 1680.703878
      - 489.716604
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      rows: 3
    rectification_matrix:
      cols: 3
      data:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      rows: 3
