/**:
  ros__parameters:
    FL_calf_controller:
      joint: FL_calf_joint
      pid:
        d: 8.0
        i: 0.0
        p: 300.0
      type: unitree_legged_control/UnitreeJointController
    FL_hip_controller:
      joint: FL_hip_joint
      pid:
        d: 5.0
        i: 0.0
        p: 100.0
      type: unitree_legged_control/UnitreeJointController
    FL_thigh_controller:
      joint: FL_thigh_joint
      pid:
        d: 8.0
        i: 0.0
        p: 300.0
      type: unitree_legged_control/UnitreeJointController
    FR_calf_controller:
      joint: FR_calf_joint
      pid:
        d: 8.0
        i: 0.0
        p: 300.0
      type: unitree_legged_control/UnitreeJointController
    FR_hip_controller:
      joint: FR_hip_joint
      pid:
        d: 5.0
        i: 0.0
        p: 100.0
      type: unitree_legged_control/UnitreeJointController
    FR_thigh_controller:
      joint: FR_thigh_joint
      pid:
        d: 8.0
        i: 0.0
        p: 300.0
      type: unitree_legged_control/UnitreeJointController
    RL_calf_controller:
      joint: RL_calf_joint
      pid:
        d: 8.0
        i: 0.0
        p: 300.0
      type: unitree_legged_control/UnitreeJointController
    RL_hip_controller:
      joint: RL_hip_joint
      pid:
        d: 5.0
        i: 0.0
        p: 100.0
      type: unitree_legged_control/UnitreeJointController
    RL_thigh_controller:
      joint: RL_thigh_joint
      pid:
        d: 8.0
        i: 0.0
        p: 300.0
      type: unitree_legged_control/UnitreeJointController
    RR_calf_controller:
      joint: RR_calf_joint
      pid:
        d: 8.0
        i: 0.0
        p: 300.0
      type: unitree_legged_control/UnitreeJointController
    RR_hip_controller:
      joint: RR_hip_joint
      pid:
        d: 5.0
        i: 0.0
        p: 100.0
      type: unitree_legged_control/UnitreeJointController
    RR_thigh_controller:
      joint: RR_thigh_joint
      pid:
        d: 8.0
        i: 0.0
        p: 300.0
      type: unitree_legged_control/UnitreeJointController
    joint_state_controller:
      publish_rate: 1000
      type: joint_state_controller/JointStateController
