/**:
  ros__parameters:
    camera_matrix:
      cols: 3
      data:
      - 801.320994
      - 0.0
      - 650.558894
      - 0.0
      - 809.347977
      - 430.852033
      - 0.0
      - 0.0
      - 1.0
      rows: 3
    camera_name: head_cam
    distortion_coefficients:
      cols: 5
      data:
      - -0.608775
      - 0.237201
      - -0.002415
      - -0.009173
      - 0.0
      rows: 1
    distortion_model: plumb_bob
    image_height: 960
    image_width: 1280
    projection_matrix:
      cols: 4
      data:
      - 552.03125
      - 0.0
      - 653.677989
      - 0.0
      - 0.0
      - 582.214111
      - 402.358005
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      rows: 3
    rectification_matrix:
      cols: 3
      data:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      rows: 3
