/**:
  ros__parameters:
    analyzers:
      computers:
        analyzers:
          b1:
            contains:
            - b1 CPU Info
            - b1 CPU Usage
            - b1 HD Usage
            - b1 Memory Usage
            path: b1
            type: diagnostic_aggregator/GenericAnalyzer
        path: Computers
        type: diagnostic_aggregator/AnalyzerGroup
      io:
        analyzers:
          joystick:
            contains: joy
            path: Joystick
            type: diagnostic_aggregator/GenericAnalyzer
          light:
            contains: light
            path: Light
            type: diagnostic_aggregator/GenericAnalyzer
        path: IO
        type: diagnostic_aggregator/AnalyzerGroup
      motors:
        analyzers:
          base:
            contains: base/
            path: Base
            type: diagnostic_aggregator/GenericAnalyzer
        path: Actuators
        type: diagnostic_aggregator/AnalyzerGroup
      safety:
        contains: safety
        path: Safety
        type: diagnostic_aggregator/GenericAnalyzer
      sensors:
        analyzers:
          battery:
            contains: bms
            path: Battery Status
            type: diagnostic_aggregator/GenericAnalyzer
          laser_front:
            contains: laser_left
            path: Scan Left
            type: diagnostic_aggregator/GenericAnalyzer
          laser_rear:
            contains: laser_right
            path: Scan Right
            type: diagnostic_aggregator/GenericAnalyzer
          laser_top:
            contains: laser_front
            path: Scan Front
            type: diagnostic_aggregator/GenericAnalyzer
        path: Sensors
        type: diagnostic_aggregator/AnalyzerGroup
    base_path: ''
    pub_rate: 1.0
