/**:
  ros__parameters:
    bodies:
    - color:
      - 1
      - 1
      - 1
      - 0.75
      footprints:
      - center:
        - -1
        - 0.0
        density: 1
        radius: 0.5
        type: circle
      - density: 1
        layers: []
        points:
        - - -.45
          - -.05
        - - -.45
          - 0.05
        - - -.35
          - 0.05
        - - -.35
          - -0.05
        sensor: true
        type: polygon
      - density: 1
        points:
        - - -.125
          - -.4
        - - -.125
          - -.3
        - - 0.125
          - -.3
        - - 0.125
          - -.4
        sensor: true
        type: polygon
      - density: 100000
        points:
        - - -.125
          - 0.4
        - - -.125
          - 0.3
        - - 0.125
          - 0.3
        - - 0.125
          - 0.4
        sensor: true
        type: polygon
      name: base
      pose:
      - 0
      - 0
      - 0
      type: dynamic
    plugins:
    - body: base
      name: turtlebot_drive
      odom_frame_id: map
      pub_rate: 10
      type: DiffDrive
    - name: tf_publisher
      publish_tf_world: true
      type: ModelTfPublisher
