/**:
  ros__parameters:
    footprint:
    - - 0.43
      - 0.35
    - - 0.43
      - -0.35
    - - -0.43
      - -0.35
    - - -0.43
      - 0.35
    footprint_clearing_enabled: false
    footprint_padding: 0.02
    observation_sources: scan
    obstacle_range: 15
    raytrace_range: 30
    robot_base_frame: $(arg frame)base_footprint
    robot_radius: 0.36
    scan:
      clearing: true
      data_type: LaserScan
      inf_is_valid: false
      marking: true
      max_obstacle_height: 2.0
      min_obstacle_height: 0.0
      sensor_frame: $(arg frame)base_link
      topic: $(arg namespace)/scan
    track_unknown: false
    track_unknown_space: false
