/**:
  ros__parameters:
    arm_elbow_joint_position_controller:
      joint: arm_elbow_joint
      type: position_controllers/JointPositionController
    arm_elbow_joint_velocity_controller:
      joint: arm_elbow_joint
      type: velocity_controllers/JointVelocityController
    arm_shoulder_lift_joint_position_controller:
      joint: arm_shoulder_lift_joint
      type: position_controllers/JointPositionController
    arm_shoulder_lift_joint_velocity_controller:
      joint: arm_shoulder_lift_joint
      type: velocity_controllers/JointVelocityController
    arm_shoulder_pan_joint_position_controller:
      joint: arm_shoulder_pan_joint
      type: position_controllers/JointPositionController
    arm_shoulder_pan_joint_velocity_controller:
      joint: arm_shoulder_pan_joint
      type: velocity_controllers/JointVelocityController
    arm_wrist_1_joint_position_controller:
      joint: arm_wrist_1_joint
      type: position_controllers/JointPositionController
    arm_wrist_1_joint_velocity_controller:
      joint: arm_wrist_1_joint
      type: velocity_controllers/JointVelocityController
    arm_wrist_2_joint_position_controller:
      joint: arm_wrist_2_joint
      type: position_controllers/JointPositionController
    arm_wrist_2_joint_velocity_controller:
      joint: arm_wrist_2_joint
      type: velocity_controllers/JointVelocityController
    arm_wrist_3_joint_position_controller:
      joint: arm_wrist_3_joint
      type: position_controllers/JointPositionController
    arm_wrist_3_joint_velocity_controller:
      joint: arm_wrist_3_joint
      type: velocity_controllers/JointVelocityController
    joint_group_position_controller:
      joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
      type: position_controllers/JointGroupPositionController
    joint_group_velocity_controller:
      joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
      type: velocity_controllers/JointGroupVelocityController
    joint_names:
    - arm_shoulder_pan_joint
    - arm_shoulder_lift_joint
    - arm_elbow_joint
    - arm_wrist_1_joint
    - arm_wrist_2_joint
    - arm_wrist_3_joint
    joint_state_controller:
      publish_rate: 50
      type: joint_state_controller/JointStateController
    joint_trajectory_controller:
      action_monitor_rate: 10
      constraints:
        arm_elbow_joint:
          goal: 0.1
          trajectory: 0.1
        arm_shoulder_lift_joint:
          goal: 0.1
          trajectory: 0.1
        arm_shoulder_pan_joint:
          goal: 0.1
          trajectory: 0.1
        arm_wrist_1_joint:
          goal: 0.1
          trajectory: 0.1
        arm_wrist_2_joint:
          goal: 0.1
          trajectory: 0.1
        arm_wrist_3_joint:
          goal: 0.1
          trajectory: 0.1
        goal_time: 1.0
        stopped_velocity_tolerance: 0.05
      joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
      state_publish_rate: 25
      stop_trajectory_duration: 0.5
      type: position_controllers/JointTrajectoryController
    max_command_silence: 0.5
