/**:
  ros__parameters:
    epsilon: 0.01
    footprint_source: /local_costmap_node/costmap
    frames_to_check: /arm_forearm_link /arm_wrist_1_link /arm_wrist_2_link /arm_wrist_3_link
      /arm_ee_link
    robot_base_frame: base_link
