/**:
  ros__parameters:
    baudrate: 38400
    devicedriver: ms-35
    devicestring: /dev/ttyUSB0
    invert_output: false
    marker_frame: base_link
    num_leds: 58
    pubmarker: false
    startup_color:
    - 0.0
    - 1.0
    - 0.0
    - 1.0
    startup_mode: Static
