/**:
  ros__parameters:
    joint_group_position_controller:
      joints:
      - torso_bottom_joint
      - torso_side_joint
      required_drive_mode: 1
      type: position_controllers/JointGroupPositionController
    joint_group_velocity_controller:
      joints:
      - torso_bottom_joint
      - torso_side_joint
      required_drive_mode: 2
      type: velocity_controllers/JointGroupVelocityController
    joint_names:
    - torso_bottom_joint
    - torso_side_joint
    joint_state_controller:
      publish_rate: 50
      type: joint_state_controller/JointStateController
    joint_trajectory_controller:
      action_monitor_rate: 10
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        torso_bottom_joint:
          goal: 0.1
          trajectory: 0.1
        torso_side_joint:
          goal: 0.1
          trajectory: 0.1
      joints:
      - torso_bottom_joint
      - torso_side_joint
      required_drive_mode: 7
      state_publish_rate: 25
      stop_trajectory_duration: 0.5
      type: position_controllers/JointTrajectoryController
    max_command_silence: 0.5
    torso_bottom_joint_position_controller:
      joint: torso_bottom_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    torso_bottom_joint_velocity_controller:
      joint: torso_bottom_joint
      required_drive_mode: 2
      type: velocity_controllers/JointVelocityController
    torso_side_joint_position_controller:
      joint: torso_side_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    torso_side_joint_velocity_controller:
      joint: torso_side_joint
      required_drive_mode: 2
      type: velocity_controllers/JointVelocityController
