/**:
  ros__parameters:
    nodes:
      b_caster_rotation_joint:
        dcf_overlay:
          607C: '-175428'
      fl_caster_rotation_joint:
        dcf_overlay:
          607C: '-54359'
      fr_caster_rotation_joint:
        dcf_overlay:
          607C: '-111597'
