/**:
  ros__parameters:
    camera_matrix:
      cols: 3
      data:
      - 904.252829
      - 0.0
      - 1087.269448
      - 0.0
      - 900.406778
      - 647.191021
      - 0.0
      - 0.0
      - 1.0
      rows: 3
    camera_name: head_cam
    distortion_coefficients:
      cols: 5
      data:
      - -0.287932
      - 0.050694
      - 0.001883
      - -0.005138
      - 0.0
      rows: 1
    distortion_model: plumb_bob
    image_height: 1536
    image_width: 2048
    projection_matrix:
      cols: 4
      data:
      - 626.475708
      - 0.0
      - 1091.475787
      - 0.0
      - 0.0
      - 672.085632
      - 608.905349
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      rows: 3
    rectification_matrix:
      cols: 3
      data:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      rows: 3
