/**:
  ros__parameters:
    nodes:
      b_caster_rotation_joint:
        dcf_overlay:
          607C: '-168132'
      fl_caster_rotation_joint:
        dcf_overlay:
          607C: '-49437'
      fr_caster_rotation_joint:
        dcf_overlay:
          607C: '71525'
