/**:
  ros__parameters:
    circumscribed_radius: 0.267
    footprint:
    - - -0.21
      - -0.21
    - - -0.21
      - 0.21
    - - 0.21
      - 0.21
    - - 0.21
      - -0.21
    inscribed_radius: 0.267
    obstacle_range: 10.0
    obstacles_layer:
      observation_sources: scan
      scan:
        clearing: true
        data_type: LaserScan
        marking: true
        sensor_frame: $(arg frame)front_laser
        topic: $(arg namespace)/scan
    raytrace_range: 15.0
    robot_base_frame: $(arg frame)base_link
    robot_radius: 0.267
    static_map_layer:
      map_topic: map
      subscribe_to_updates: true
