/**:
  ros__parameters:
    bodies:
    - color:
      - 0.2
      - 0.8
      - 0.2
      - 1.0
      footprints:
      - center:
        - 0.0
        - 0.0
        collision: true
        density: 1
        friction: 0.1
        layers:
        - all
        radius: 0.225
        restitution: 0
        sensor: false
        type: circle
      name: base_link
      pose:
      - 0
      - 0
      - 0
      type: dynamic
    plugins:
    - body: base_link
      name: diff_drive
      odom_frame_id: odom
      odom_pub: odom
      pub_rate: 10
      twist_sub: cmd_vel
      type: DiffDrive
    - angle:
        increment: 0.0087
        max: 2.39983
        min: -2.39983
      body: base_link
      broadcast_tf: true
      frame: hokuyo_link
      name: static_laser
      noise_std_dev: 0.0
      origin:
      - 0.08
      - 0.0
      - 0.2015
      range: 50.0
      topic: scan
      type: Laser
      update_rate: 10
    - name: tf_publisher
      publish_tf_world: false
      type: ModelTfPublisher
