/**:
  ros__parameters:
    layers:
    - color:
      - 0
      - 1
      - 0
      - 1
      map: map.yaml
      name: static
    properties:
      position_iterations: 10
      velocity_iterations: 10
