/**:
  ros__parameters:
    nodes:
      b_caster_rotation_joint:
        dcf_overlay:
          607C: '7649.5'
      fl_caster_rotation_joint:
        dcf_overlay:
          607C: '129950.0'
      fr_caster_rotation_joint:
        dcf_overlay:
          607C: '-109273.5'
