/**:
  ros__parameters:
    defaults:
      eds_file: robots/common/Schunk_0_63.dcf
      eds_pkg: cob_hardware_config
      pos_from_device: obj6064/1000000/2
      pos_to_device: rint(pos*1000000*2)
      vel_from_device: obj606C/1000000/2
      vel_to_device: rint(vel*1000000*2)
    nodes:
      motor:
        id: 12
        joint: gripper_left_finger_left_joint
    sync:
      interval_ms: 10
      overflow: 0
