/**:
  ros__parameters:
    arm_right_1_joint_position_controller:
      joint: arm_right_1_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    arm_right_1_joint_velocity_controller:
      joint: arm_right_1_joint
      required_drive_mode: 2
      type: velocity_controllers/JointVelocityController
    arm_right_2_joint_position_controller:
      joint: arm_right_2_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    arm_right_2_joint_velocity_controller:
      joint: arm_right_2_joint
      required_drive_mode: 2
      type: velocity_controllers/JointVelocityController
    arm_right_3_joint_position_controller:
      joint: arm_right_3_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    arm_right_3_joint_velocity_controller:
      joint: arm_right_3_joint
      required_drive_mode: 2
      type: velocity_controllers/JointVelocityController
    arm_right_4_joint_position_controller:
      joint: arm_right_4_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    arm_right_4_joint_velocity_controller:
      joint: arm_right_4_joint
      required_drive_mode: 2
      type: velocity_controllers/JointVelocityController
    arm_right_5_joint_position_controller:
      joint: arm_right_5_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    arm_right_5_joint_velocity_controller:
      joint: arm_right_5_joint
      required_drive_mode: 2
      type: velocity_controllers/JointVelocityController
    arm_right_6_joint_position_controller:
      joint: arm_right_6_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    arm_right_6_joint_velocity_controller:
      joint: arm_right_6_joint
      required_drive_mode: 2
      type: velocity_controllers/JointVelocityController
    arm_right_7_joint_position_controller:
      joint: arm_right_7_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    arm_right_7_joint_velocity_controller:
      joint: arm_right_7_joint
      required_drive_mode: 2
      type: velocity_controllers/JointVelocityController
    joint_group_position_controller:
      joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
      required_drive_mode: 1
      type: position_controllers/JointGroupPositionController
    joint_group_velocity_controller:
      joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
      required_drive_mode: 2
      type: velocity_controllers/JointGroupVelocityController
    joint_names:
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
    joint_state_controller:
      publish_rate: 50
      type: joint_state_controller/JointStateController
    joint_trajectory_controller:
      action_monitor_rate: 10
      constraints:
        arm_right_1_joint:
          goal: 0.1
          trajectory: 0.1
        arm_right_2_joint:
          goal: 0.1
          trajectory: 0.1
        arm_right_3_joint:
          goal: 0.1
          trajectory: 0.1
        arm_right_4_joint:
          goal: 0.1
          trajectory: 0.1
        arm_right_5_joint:
          goal: 0.1
          trajectory: 0.1
        arm_right_6_joint:
          goal: 0.1
          trajectory: 0.1
        arm_right_7_joint:
          goal: 0.1
          trajectory: 0.1
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
      joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
      required_drive_mode: 7
      state_publish_rate: 25
      stop_trajectory_duration: 0.5
      type: position_controllers/JointTrajectoryController
    max_command_silence: 0.5
