/**:
  ros__parameters:
    baud: 500000
    frame_id: base_laser_left_link
    inverted: false
    port: /dev/ttyScanLeft
    publish_frequency: 12
    scan_cycle_time: 0.04
    scan_duration: 0.025
    scan_id: 7
    scan_intervals:
    - - -1.5
      - 1.5
