/**:
  ros__parameters:
    enable_light: true
    enable_sound: false
    light_components:
    - light_torso
    num_leds: 72
    sound_components:
    - sound
    threshold_critical: 5
    threshold_error: 10
    threshold_warning: 20
