/**:
  ros__parameters:
    defaults:
      dcf_overlay:
        1016sub1: '0x7F0064'
        '6083': '1000000'
        '6084': '1000000'
        6099sub1: '100000'
        6099sub2: '10000'
        60C5: '1000000'
        60C6: '1000000'
      eds_file: robots/common/Elmo.dcf
      eds_pkg: cob_hardware_config
      eff_from_device: obj6078/1000.0*9.76
    drive_wheel:
      dcf_overlay: &id001
        '6098': '35'
      eff_from_device: obj6078/1000.0*14.14
      vel_from_device: 'p1 != p1 || obj2041 == t1 ? 0 : deg2rad(1000*norm(obj6064-p1,-36000000,36000000)/norm(obj2041-t1,0,2^32)),
        p1=p0, p0 = obj6064, t1 = t0, t0 = obj2041'
    heartbeat:
      msg: 77f#05
      rate: 20
    nodes:
      b_caster_r_wheel_joint:
        dcf_overlay: *id001
        eff_from_device: obj6078/1000.0*14.14
        id: 4
        vel_from_device: 'p1 != p1 || obj2041 == t1 ? 0 : deg2rad(1000*norm(obj6064-p1,-36000000,36000000)/norm(obj2041-t1,0,2^32)),
          p1=p0, p0 = obj6064, t1 = t0, t0 = obj2041'
      b_caster_rotation_joint:
        dcf_overlay:
          '6098': '19'
        id: 3
      fl_caster_r_wheel_joint:
        dcf_overlay: *id001
        eff_from_device: obj6078/1000.0*14.14
        id: 2
        vel_from_device: 'p1 != p1 || obj2041 == t1 ? 0 : deg2rad(1000*norm(obj6064-p1,-36000000,36000000)/norm(obj2041-t1,0,2^32)),
          p1=p0, p0 = obj6064, t1 = t0, t0 = obj2041'
      fl_caster_rotation_joint:
        dcf_overlay:
          '6098': '19'
        id: 1
      fr_caster_r_wheel_joint:
        dcf_overlay: *id001
        eff_from_device: obj6078/1000.0*14.14
        id: 6
        vel_from_device: 'p1 != p1 || obj2041 == t1 ? 0 : deg2rad(1000*norm(obj6064-p1,-36000000,36000000)/norm(obj2041-t1,0,2^32)),
          p1=p0, p0 = obj6064, t1 = t0, t0 = obj2041'
      fr_caster_rotation_joint:
        dcf_overlay:
          '6098': '19'
        id: 5
    sync:
      interval_ms: 20
      overflow: 0
