/**:
  ros__parameters:
    joint_names:
    - fl_caster_rotation_joint
    - fl_caster_r_wheel_joint
    - fr_caster_rotation_joint
    - fr_caster_r_wheel_joint
    - b_caster_rotation_joint
    - b_caster_r_wheel_joint
    joint_state_controller:
      publish_rate: 50
      type: joint_state_controller/JointStateController
    twist_controller:
      defaults:
        steer_ctrl:
          d_phi_max: 10.0
          damp: 2.75
          dd_phi_max: 40.0
          spring: 15.0
          virt_mass: 0.1
      pub_divider: 1
      required_drive_mode: 3
      timeout: 0.5
      type: cob_omni_drive_controller/WheelController
      wheels:
      - drive: fl_caster_r_wheel_joint
        steer: fl_caster_rotation_joint
      - drive: b_caster_r_wheel_joint
        steer: b_caster_rotation_joint
        steer_neutral_position: -180.0
      - drive: fr_caster_r_wheel_joint
        steer: fr_caster_rotation_joint
