/**:
  ros__parameters:
    global_frame: odom_combined
    goal_abortion_time: 5.0
    goal_threshold: 0.02
    goal_threshold_rot: 0.06
    kp: 3.0
    kp_rot: 2.0
    kv: 2.5
    kv_rot: 2.0
    robot_frame: base_link
    slow_down_distance: 0.25
    speed_threshold: 0.02
    speed_threshold_rot: 0.02
    virt_mass: 0.5
    virt_mass_rot: 0.5
    vmax: 0.09
    vtheta_max: 0.3
