/**:
  ros__parameters:
    distance_tolerance: 0.1
    dock_dist_threshold: 0.15
    intensity_lower_threshold: 200
    intensity_upper_threshold: 10000
    stations:
    - approach_poses:
      - - -0.76
        - 0.0
        - 0.0
      - - -0.56
        - 0.0
        - 0.0
      - - -0.47
        - 0.0
        - -0.02
      departure_poses:
      - - -0.8
        - 0.0
        - 0.0
      frame_id: station_charger
      reflector_distance: 0.28
      stop_condition:
        compare_value: true
        message_field: charging
        topic: /power_state
    - approach_poses:
      - - -2.2
        - 0.0
        - 0.0
      - - -0.6
        - 0.0
        - -0.035
      - - -0.38
        - 0.0
        - -0.035
      - - -0.312
        - 0.0
        - -0.035
      departure_poses:
      - - -0.38
        - 0.0
        - -0.035
      - - -0.6
        - 0.0
        - -0.035
      - - -2.2
        - 0.0
        - 0.0
      frame_id: station_travel_box
      reflector_distance: 0.95
    undock_dist_threshold: 1.0
    update_rate: 0.25
