/**:
  ros__parameters:
    head_1_joint_position_controller:
      joint: head_1_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    head_1_joint_velocity_controller:
      joint: head_1_joint
      required_drive_mode: 3
      type: velocity_controllers/JointVelocityController
    head_2_joint_position_controller:
      joint: head_2_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    head_2_joint_velocity_controller:
      joint: head_2_joint
      required_drive_mode: 3
      type: velocity_controllers/JointVelocityController
    head_3_joint_position_controller:
      joint: head_3_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    head_3_joint_velocity_controller:
      joint: head_3_joint
      required_drive_mode: 3
      type: velocity_controllers/JointVelocityController
    joint_group_position_controller:
      joints:
      - head_1_joint
      - head_2_joint
      - head_3_joint
      required_drive_mode: 1
      type: position_controllers/JointGroupPositionController
    joint_group_velocity_controller:
      joints:
      - head_1_joint
      - head_2_joint
      - head_3_joint
      required_drive_mode: 3
      type: velocity_controllers/JointGroupVelocityController
    joint_names:
    - head_1_joint
    - head_2_joint
    - head_3_joint
    joint_state_controller:
      publish_rate: 50
      type: joint_state_controller/JointStateController
    joint_trajectory_controller:
      action_monitor_rate: 10
      constraints:
        goal_time: 0.6
        head_1_joint:
          goal: 0.1
          trajectory: 0.1
        head_2_joint:
          goal: 0.1
          trajectory: 0.1
        head_3_joint:
          goal: 0.1
          trajectory: 0.1
        stopped_velocity_tolerance: 0.05
      joints:
      - head_1_joint
      - head_2_joint
      - head_3_joint
      required_drive_mode: 7
      state_publish_rate: 25
      stop_trajectory_duration: 0.5
      type: position_controllers/JointTrajectoryController
    max_command_silence: 0.5
