/**:
  ros__parameters:
    defaults:
      eds_file: robots/common/Elmo.dcf
      eds_pkg: cob_hardware_config
      motor_layer:
        switching_state: 4
      vel_from_device: 'v != v ? v=0 : v=smooth(deg2rad(obj606c/1000.0),v,0.3)'
    nodes:
    - dcf_overlay:
        '6083': '300000'
        '6084': '300000'
        60C5: '300000'
        60C6: '1000000'
      id: 70
      name: head_1_joint
    - dcf_overlay:
        '6083': '200000'
        '6084': '200000'
        60C5: '200000'
        60C6: '1000000'
      id: 71
      name: head_2_joint
    - dcf_overlay:
        '6083': '300000'
        '6084': '300000'
        60C5: '300000'
        60C6: '1000000'
      id: 72
      name: head_3_joint
    sync:
      interval_ms: 10
      overflow: 0
