/**:
  ros__parameters:
    baudrate: 38400
    devicedriver: stageprofi
    devicestring: /dev/ttyLED
    invert_output: false
    led_offset: 5
    marker_frame: /torso_center_link
    num_leds: 72
    pubmarker: true
    startup_color:
    - 0.0
    - 1.0
    - 0.5
    - 0.4
    startup_mode: Breath
