/**:
  ros__parameters:
    baudrate: 38400
    devicedriver: stageprofi
    devicestring: /dev/ttyLED
    invert_output: false
    marker_frame: base_link
    num_leds: 3
    pubmarker: true
    startup_color:
    - 0.0
    - 1.0
    - 0.5
    - 0.4
    startup_mode: Static
