/**:
  ros__parameters:
    footprint:
    - - 0.43
      - 0.35
    - - 0.43
      - -0.35
    - - -0.43
      - -0.35
    - - -0.43
      - 0.35
    footprint_padding: 0.02
    height: 5.0
    obstacle_layer_0:
      enabled: true
      footprint_clearing_enabled: false
      max_obstacle_height: 2.0
      min_obstacle_height: 0.0
      observation_sources: scan_unified_filtered
      obstacle_range: 15.0
      raytrace_range: 30.0
      scan_unified_filtered:
        clearing: true
        data_type: LaserScan
        inf_is_valid: false
        marking: true
        sensor_frame: $(arg frame)base_link
        topic: $(arg namespace)/scan_unified
      track_unknown: false
      track_unknown_space: false
    plugins:
    - name: obstacle_layer_0
      type: costmap_2d::ObstacleLayer
    publish_frequency: 5.0
    resolution: 0.05
    robot_base_frame: $(arg frame)base_footprint
    rolling_window: true
    update_frequency: 5.0
    width: 5.0
