/**:
  ros__parameters:
    check_core_temps: true
    check_ipmi_tool: false
    core_load_error: 110
    core_load_warn: 90
    core_temp_error: 97
    core_temp_warn: 95
    load1_threshold: 10
    load5_threshold: 10
    mem_error: 1
    mem_warn: 25
    num_cores: 4
