/**:
  ros__parameters:
    defaults:
      dcf_overlay:
        1016sub1: '0x7F0064'
      eds_file: robots/common/Elmo.dcf
      eds_pkg: cob_hardware_config
      motor_layer:
        switching_state: 4
      vel_from_device: 'v != v ? v=0 : v=smooth(deg2rad(obj606c/1000.0),v,0.3)'
    heartbeat:
      msg: 77f#05
      rate: 20
    nodes:
    - dcf_overlay:
        '6083': '200000'
        '6084': '200000'
        60C5: '200000'
        60C6: '200000'
      id: 32
      name: torso_2_joint
    - dcf_overlay:
        '6083': '200000'
        '6084': '200000'
        60C5: '200000'
        60C6: '200000'
      id: 33
      name: torso_3_joint
    sync:
      interval_ms: 10
      overflow: 0
