/**:
  ros__parameters:
    topics:
    - name: collision_velocity_filter
      priority: 10
      timeout: 0.25
      topic: twist_mux/command_safe
    - name: navigation
      priority: 20
      timeout: 0.25
      topic: twist_mux/command_navigation
    - name: syncmm
      priority: 60
      timeout: 0.5
      topic: twist_mux/command_syncmm
    - name: script_server
      priority: 70
      timeout: 0.5
      topic: twist_mux/command_script_server
    - name: teleop_keyboard
      priority: 80
      timeout: 0.5
      topic: twist_mux/command_teleop_keyboard
    - name: teleop_android
      priority: 90
      timeout: 0.5
      topic: twist_mux/command_teleop_android
    - name: teleop_joystick
      priority: 100
      timeout: 0.25
      topic: twist_mux/command_teleop_joy
