/**:
  ros__parameters:
    diff_drive_controller:
      angular:
        z:
          has_acceleration_limits: true
          has_velocity_limits: true
          max_acceleration: 0.5
          max_velocity: 1.0
      base_frame_id: base_link
      cmd_vel_timeout: 0.5
      enable_odom_tf: false
      estimate_velocity_from_position: false
      left_wheel:
      - right_dd_wheel_joint
      linear:
        x:
          has_acceleration_limits: true
          has_velocity_limits: true
          max_acceleration: 1.0
          max_velocity: 1.5
      odom_frame_id: odom
      pose_covariance_diagonal:
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.03
      publish_rate: 50
      right_wheel:
      - left_dd_wheel_joint
      twist_covariance_diagonal:
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.03
      type: diff_drive_controller/DiffDriveController
      velocity_rolling_window_size: 2
      wheel_radius: 0.175
      wheel_radius_multiplier: 1.0
      wheel_separation: 0.492
      wheel_separation_multiplier: 1.0
    gazebo_ros_control:
      pid_gains:
        left_dd_wheel_joint:
          d: 0.005
          i: 0.1
          p: 6.0
        right_dd_wheel_joint:
          d: 0.005
          i: 0.1
          p: 6.0
    joint_state_controller:
      publish_rate: 50
      type: joint_state_controller/JointStateController
