/**:
  ros__parameters:
    nodes:
      b_caster_rotation_joint:
        dcf_overlay:
          607C: '-79121'
      fl_caster_rotation_joint:
        dcf_overlay:
          607C: '43764'
      fr_caster_rotation_joint:
        dcf_overlay:
          607C: '162470'
