/**:
  ros__parameters:
    nodes:
      b_caster_rotation_joint:
        dcf_overlay:
          607C: '9477.5'
      fl_caster_rotation_joint:
        dcf_overlay:
          607C: '36418.0'
      fr_caster_rotation_joint:
        dcf_overlay:
          607C: '-111057.0'
