/**:
  ros__parameters:
    bodies:
    - color:
      - 1.0
      - 0.64
      - 0.0
      - 1.0
      footprints:
      - collision: true
        density: 1
        friction: 0.1
        layers:
        - all
        points:
        - - 0.513
          - 0.364
        - - 0.513
          - -0.364
        - - -0.513
          - -0.364
        - - -0.513
          - 0.364
        restitution: 0
        sensor: false
        type: polygon
      name: base_link
      pose:
      - 0
      - 0
      - 0
      type: dynamic
    plugins:
    - body: base_link
      name: diff_drive
      odom_frame_id: odom
      odom_pub: odom
      pub_rate: 10
      twist_sub: cmd_vel
      type: DiffDrive
    - angle:
        increment: 0.00436332312
        max: 1.5707963267948966
        min: -1.5707963267948966
      body: base_link
      broadcast_tf: true
      frame: scan_link
      name: static_laser
      noise_std_dev: 0.0
      origin:
      - 0.0
      - 0.0
      - 0.0
      range: 30.0
      topic: scan
      type: Laser
      update_rate: 10
    - name: tf_publisher
      publish_tf_world: false
      type: ModelTfPublisher
