/**:
  ros__parameters:
    nodes:
      b_caster_rotation_joint:
        dcf_overlay:
          607C: '9224.5'
      fl_caster_rotation_joint:
        dcf_overlay:
          607C: '130636.5'
      fr_caster_rotation_joint:
        dcf_overlay:
          607C: '-113222.5'
