/**:
  ros__parameters:
    conservative_reset_dist: 0.1
    controller_frequency: 5.0
    controller_patience: 3.0
    oscillation_distance: 0.2
    oscillation_timeout: 10.0
    planner_frequency: 0.5
    planner_patience: 5.0
    robot_frame: $(arg frame)base_link
    shutdown_costmaps: false
