/**:
  ros__parameters:
    TebLocalPlannerROS:
      acc_lim_theta: 0.5
      acc_lim_x: 0.5
      alternative_time_cost: false
      costmap_obstacles_behind_robot_dist: 1.0
      dt_ref: 0.5
      footprint_model:
        front_offset: 0.2
        front_radius: 0.2
        line_end:
        - 0.3
        - 0.0
        line_start:
        - -0.3
        - 0.0
        radius: 0.2
        rear_offset: 0.2
        rear_radius: 0.2
        type: point
        vertices:
        - - 0.25
          - -0.05
        - - 0.18
          - -0.05
        - - 0.18
          - -0.18
        - - -0.19
          - -0.18
        - - -0.25
          - 0
        - - -0.19
          - 0.18
        - - 0.18
          - 0.18
        - - 0.18
          - 0.05
        - - 0.25
          - 0.05
      max_vel_theta: 0.3
      max_vel_x: 0.8
      max_vel_x_backwards: 0.8
      min_obstacle_dist: 0.4
      min_turning_radius: 0.0
      obstacle_keypoint_offset: 0.1
      obstacle_poses_affected: 30
      simple_exploration: false
      weight_obstacle: 50
