/**:
  ros__parameters:
    actions:
      continuous:
        angular_range:
        - -1.0
        - 1.0
        linear_range:
          x:
          - -2.78
          - 2.78
          y:
          - -2.78
          - 2.78
      discrete:
      - angular: 0.0
        linear: 2.78
        name: move_forward
      - angular: 0.0
        linear: -0.15
        name: move_backward
      - angular: 0.35
        linear: 0.15
        name: turn_left
      - angular: -0.35
        linear: 0.15
        name: turn_right
      - angular: 0.75
        linear: 0.0
        name: turn_strong_left
      - angular: -0.75
        linear: 0.0
        name: turn_strong_right
      - angular: 0.0
        linear: 0.0
        name: stop
    is_holonomic: true
    laser:
      angle:
        increment: 0.00613294
        max: 2.0944
        min: -2.0944
      num_beams: 683
      range: 5.6
      update_rate: 10
    robot_base_frame: base_link
    robot_model: rto_lab
    robot_radius: 0.225
    robot_sensor_frame: laser_link
