/**:
  ros__parameters:
    circumscribed_radius: 0.755
    footprint:
    - - -0.285
      - 0.285
    - - -0.285
      - -0.285
    - - 0.285
      - -0.285
    - - 0.285
      - 0.285
    inscribed_radius: 0.755
    observation_sources: scan
    robot_base_frame: $(arg frame)base_footprint
    robot_radius: 0.755
    scan:
      clearing: true
      data_type: LaserScan
      marking: true
      sensor_frame: $(arg frame)base_laser_front_link
      topic: $(arg namespace)/scan
