/**:
  ros__parameters:
    nodes:
      b_caster_rotation_joint:
        dcf_overlay:
          607C: '-81439'
      fl_caster_rotation_joint:
        dcf_overlay:
          607C: '41401'
      fr_caster_rotation_joint:
        dcf_overlay:
          607C: '161615'
