/**:
  ros__parameters:
    bodies:
    - color:
      - 0.2
      - 0.8
      - 0.2
      - 1.0
      footprints:
      - collision: true
        density: 1
        friction: 0.1
        layers:
        - all
        points:
        - - -0.19
          - -0.29
        - - -0.19
          - 0.29
        - - 0.19
          - 0.29
        - - 0.19
          - -0.29
        restitution: 0
        sensor: false
        type: polygon
      name: base_footprint
      pose:
      - 0
      - 0
      - 0
      type: dynamic
    plugins:
    - body: base_footprint
      name: diff_drive
      odom_frame_id: odom
      odom_pub: odom
      pub_rate: 10
      twist_sub: cmd_vel
      type: DiffDrive
    - angle:
        increment: 0.00612393906
        max: 1.56466042995
        min: -1.57079637051
      body: base_footprint
      broadcast_tf: true
      frame: base_laser_front_link
      name: static_laser
      noise_std_dev: 0.0
      origin:
      - 0.0
      - 0.0
      - 0.0
      range: 5.6
      topic: scan
      type: Laser
      update_rate: 10
    - name: tf_publisher
      publish_tf_world: false
      type: ModelTfPublisher
