planners:
  - name: NavfnROS
    type: navfn/NavfnROS

shutdown_costmaps: false
planner_frequency: 0.1
planner_patience: 5.0
inter_frequency: 5.0
inter_patience: 5.0
controller_frequency: 10.0
controller_patience: 5.0
conservative_reset_dist: 3.0
oscillation_timeout: 10.0
oscillation_distance: 0.2
recovery_behavior_enabled: false