/**:
  ros__parameters:
    conservative_reset_dist: 3.0
    controller_frequency: 10.0
    controller_patience: 5.0
    inter_frequency: 5.0
    inter_patience: 5.0
    oscillation_distance: 0.2
    oscillation_timeout: 10.0
    planner_frequency: 5.0
    planner_patience: 5.0
    planners:
    - name: NavfnROS
      type: navfn/NavfnROS
    recovery_behavior_enabled: false
    shutdown_costmaps: false
