/**:
  ros__parameters:
    MpcLocalPlannerROS:
      footprint_model:
        type: polygon
        vertices:
        - - -0.285
          - 0.18
        - - -0.285
          - -0.18
        - - 0.285
          - -0.18
        - - 0.285
          - 0.18
      grid:
        type: fd_grid
        variable_grid:
          enable: false
      planning:
        objective:
          type: quadratic_form
        terminal_constraint:
          type: none
        terminal_cost:
          type: quadratic
      robot:
        type: unicycle
        unicycle:
          acc_lim_theta: 1.0
          acc_lim_x: 1.25
          acc_lim_y: 1.25
          dec_lim_x: 1.25
          max_vel_theta: 1.2
          max_vel_x: 0.8
          max_vel_x_backwards: 0.8
          max_vel_y: 0.8
      solver:
        lsq_lm:
          iterations: 10
        type: ipopt
