/**:
  ros__parameters:
    camera_matrix:
      cols: 3
      data:
      - 845.812494
      - 0.0
      - 1103.001583
      - 0.0
      - 832.140012
      - 720.133169
      - 0.0
      - 0.0
      - 1.0
      rows: 3
    camera_name: head_cam
    distortion_coefficients:
      cols: 5
      data:
      - -0.25463
      - 0.0362
      - 0.003246
      - 0.000355
      - 0.0
      rows: 1
    distortion_model: plumb_bob
    image_height: 1536
    image_width: 2048
    projection_matrix:
      cols: 4
      data:
      - 653.072021
      - 0.0
      - 1065.820759
      - 0.0
      - 0.0
      - 606.541748
      - 714.918738
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      rows: 3
    rectification_matrix:
      cols: 3
      data:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      rows: 3
