/**:
  ros__parameters:
    nodes:
      b_caster_rotation_joint:
        dcf_overlay:
          607C: '9528.0'
      fl_caster_rotation_joint:
        dcf_overlay:
          607C: '127621.5'
      fr_caster_rotation_joint:
        dcf_overlay:
          607C: '-108166.0'
