/**:
  ros__parameters:
    cost_scaling_factor: 5.0
    inflation_radius: 1.0
    map_type: costmap
    obstacle_range: 5.0
    publish_frequency: 5.0
    raytrace_range: 5.5
    semantic_layer:
      observation_sources: pedestrian pedestrian_moving pedestrian_type pedestrian_vel_x
        pedestrian_vel_y social_state
      pedestrian:
        topic: /crowdsim_agents/semantic/pedestrian
      pedestrian_moving:
        topic: /crowdsim_agents/semantic/pedestrian_moving
      pedestrian_type:
        topic: /crowdsim_agents/semantic/pedestrian_type
      pedestrian_vel_x:
        topic: /crowdsim_agents/semantic/pedestrian_vel_x
      pedestrian_vel_y:
        topic: /crowdsim_agents/semantic/pedestrian_vel_y
      social_state:
        topic: /crowdsim_agents/semantic/social_state
    transform_tolerance: 0.2
    update_frequency: 5.0
