/**:
  ros__parameters:
    human obstacle safety distance radius:
      adult: 1.0
      child: 1.2
      elder: 1.5
      forklift: 1.8
      servicerobot: 1.6
    obstacle radius:
      adult: 0.32
      child: 0.25
      elder: 0.3
      forklift: 0.7
      random_wanderer: 0.4
      servicerobot: 0.6
    robot obstacle safety distance radius:
      random_wanderer: 1.8
    safety distance factor:
      BackUp: 1.1
      Driving: 1.4
      GroupTalking: 0.8
      GroupWalking: 1.1
      LiftingForks: 0.6
      Listening: 0.8
      ListeningAndWalking: 0.9
      Loading: 0.7
      LoweringForks: 0.8
      None: 1.0
      Queueing: 1.0
      ReachedShelf: 0.5
      Running: 1.4
      Shopping: 1.0
      StateClearingGoal: 2.0
      StateDrivingToInteraction: 1.4
      StateFollowingGuide: 2.0
      StateGuideToGoal: 2.0
      StateProvidingService: 0.6
      StateReceivingService: 0.6
      StateRequestingFollower: 2.0
      StateRequestingGuide: 0.5
      StateRequestingService: 0.6
      StateWaitForTimer: 0.5
      StateWaitForTrigger: 0.5
      Talking: 0.6
      TalkingAndWalking: 0.9
      TellStory: 1.0
      Waiting: 1.0
      Walking: 1.1
      Working: 0.6
