/**:
  ros__parameters:
    nodes:
      b_caster_rotation_joint:
        dcf_overlay:
          607C: '-172226'
      fl_caster_rotation_joint:
        dcf_overlay:
          607C: '-52047'
      fr_caster_rotation_joint:
        dcf_overlay:
          607C: '67092'
