/**:
  ros__parameters:
    apply_ramp: false
    axis_vx: 1
    axis_vy: 0
    axis_yaw: 3
    components:
      base:
        twist_max_acc:
        - 0.5
        - 0.5
        - 0.7
        twist_max_velocity:
        - 0.3
        - 0.2
        - 0.3
        twist_safety_topic_name: /base/collision_velocity_filter/command
        twist_topic_name: /base/twist_mux/command_teleop_joy
    deadman_button: 5
    init_button: 7
    joy_num_axes: 6
    joy_num_modes: 1
    run_factor: 2.0
    safety_button: 4
