/**:
  ros__parameters:
    bodies:
    - color:
      - 0.8
      - 0.8
      - 0.8
      - 1.0
      footprints:
      - collision: true
        density: 1
        friction: 0.1
        layers:
        - all
        points:
        - - 0.48
          - -0.4
        - - 0.48
          - 0.4
        - - -0.48
          - 0.4
        - - -0.48
          - -0.4
        restitution: 0
        sensor: false
        type: polygon
      name: base_link
      pose:
      - 0
      - 0
      - 0
      type: dynamic
    plugins:
    - body: base_link
      name: diff_drive
      odom_frame_id: odom
      odom_pub: odom
      pub_rate: 10
      twist_sub: cmd_vel
      type: DiffDrive
    - angle:
        increment: 0.00654497222
        max: 2.35619
        min: -2.35619
      body: base_link
      broadcast_tf: true
      frame: front_laser
      name: static_laser
      noise_std_dev: 0.0
      origin:
      - 0.0
      - 0.0
      - 0.0
      range: 10.0
      topic: scan
      type: Laser
      update_rate: 10
    - name: tf_publisher
      publish_tf_world: false
      type: ModelTfPublisher
