/**:
  ros__parameters:
    DwaLocalPlannerROS:
      acc_lim_theta: 3.2
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      controller_frequency: 10.0
      max_vel_theta: 1.82
      max_vel_trans: 0.28
      max_vel_x: 0.28
      max_vel_y: 0.0
      min_vel_theta: 0.9
      min_vel_trans: 0.13
      min_vel_x: -0.28
      min_vel_y: 0.0
      sim_time: 2.0
