/**:
  ros__parameters:
    nodes:
      b_caster_rotation_joint:
        dcf_overlay:
          607C: '8358.0'
      fl_caster_rotation_joint:
        dcf_overlay:
          607C: '130546.0'
      fr_caster_rotation_joint:
        dcf_overlay:
          607C: '-112508.0'
