/**:
  ros__parameters:
    DwaLocalPlannerROS:
      acc_lim_th: 3.2
      acc_lim_x: 2.5
      forward_point_distance: 0.0
      goal_distance_bias: 32.0
      max_rot_vel: 0.6
      max_trans_vel: 0.3
      max_vel_x: 1.1
      max_vel_y: 0.2
      min_rot_vel: 0.01
      min_trans_vel: 0.01
      min_vel_x: -1.1
      min_vel_y: -0.2
      occdist_scale: 0.01
      path_distance_bias: 24.0
      penalize_negative_x: false
      rot_stopped_vel: 0.01
      sim_granularity: 0.017
      sim_period: 0.1
      sim_time: 1.7
      trans_stopped_vel: 0.01
      vtheta_samples: 20
      vx_samples: 3
      vy_samples: 10
      xy_goal_tolerance: 0.2
