/**:
  ros__parameters:
    acc_lim_theta: 0.4
    acc_lim_x: 0.3
    acc_lim_y: 0.3
    add_invisible_humans: true
    agent_acc_lim_theta: 0.8
    agent_acc_lim_x: 0.6
    agent_acc_lim_y: 0.3
    agent_min_samples: 3
    agent_radius: 0.31
    agent_robot_ttc_scale_alpha: 1.0
    agent_robot_ttcplus_scale_alpha: 1.0
    allow_init_with_backwards_motion: false
    approach_angle: 3.14
    approach_dist: 1.0
    approach_id: 1
    cap_optimaltime_penalty: true
    costmap_converter/CostmapToLinesDBSRANSAC:
      cluster_max_distance: 0.8
      cluster_min_pts: 2
      convex_hull_min_pt_separation: 0.1
      ransac_convert_outlier_pts: true
      ransac_filter_remaining_outlier_pts: false
      ransac_inlier_distance: 0.15
      ransac_min_inliers: 10
      ransac_no_iterations: 1500
      ransac_remainig_outliers: 3
    costmap_converter_plugin: costmap_converter::CostmapToLinesDBSRANSAC
    costmap_converter_rate: 10
    costmap_converter_spin_thread: true
    costmap_obstacles_behind_robot_dist: 0.5
    disable_warm_start: true
    dt_hysteresis: 0.1
    dt_ref: 0.3
    enable_homotopy_class_planning: false
    enable_multithreading: true
    feasibility_check_no_poses: 2
    footprint_model:
      front_offset: 0.2
      front_radius: 0.2
      line_end:
      - 0.3
      - 0.0
      line_start:
      - -0.3
      - 0.0
      radius: 0.34
      rear_offset: 0.2
      rear_radius: 0.2
      type: circular
      vertices:
      - - -0.325
        - -0.325
      - - -0.325
        - 0.325
      - - 0.325
        - 0.325
      - - 0.46
        - 0.0
      - - 0.325
        - -0.325
    free_goal_vel: true
    global_plan_overwrite_orientation: true
    global_plan_viapoint_sep: 0.2
    h_signature_prescaler: 0.5
    h_signature_threshold: 0.1
    holonomic_robot: true
    include_costmap_obstacles: true
    invisible_human_threshold: 0.8
    max_agent_vel_theta: 1.1
    max_agent_vel_x: 1.3
    max_agent_vel_x_backwards: 0.01
    max_agent_vel_y: 0.4
    max_global_plan_lookahead_dist: 0.0
    max_number_classes: 4
    max_vel_theta: 1.2
    max_vel_x: 0.7
    max_vel_x_backwards: 0.4
    max_vel_y: 0.7
    min_agent_dist: 0.4
    min_agent_robot_dist: 0.6
    min_obstacle_dist: 0.2
    min_turning_radius: 0.0
    min_vel_theta: 0.1
    min_vel_x: 0.02
    no_inner_iterations: 8
    no_outer_iterations: 4
    nominal_agent_vel_x: 1.1
    obstacle_cost_mult: 1.0
    obstacle_heading_threshold: 0.45
    obstacle_keypoint_offset: 0.1
    obstacle_poses_affected: 1
    optimization_activate: true
    optimization_verbose: false
    penalty_epsilon: 0.01
    planning_mode: 1
    pose_array_z_scale: 0.5
    predict_agent_behind_robot: true
    predict_agent_goal: false
    publish_agents_global_plans: true
    publish_agents_local_plan_fp_poses: true
    publish_agents_local_plan_poses: true
    publish_agents_local_plans: true
    publish_robot_global_plan: true
    publish_robot_local_plan: true
    publish_robot_local_plan_fp_poses: true
    publish_robot_local_plan_poses: true
    rel_vel_cost_threshold: 1.5
    roadmap_graph_area_width: 5
    roadmap_graph_no_samples: 15
    robot_radius: 0.47
    scale_agent_robot_ttc_c: false
    scale_agent_robot_ttcplus_c: false
    selection_alternative_time_cost: false
    shrink_horizon_backup: true
    simple_exploration: true
    teb_autosize: true
    ttc_threshold: 5.0
    ttclosest_threshold: 1.0
    ttcplus_threshold: 5.0
    ttcplus_timer: 1.0
    type: 0
    use_agent_agent_safety_c: true
    use_agent_robot_rel_vel_c: true
    use_agent_robot_safety_c: true
    use_agent_robot_ttc_c: false
    use_agent_robot_ttclosest_c: false
    use_agent_robot_ttcplus_c: false
    use_agent_robot_visi_c: true
    use_external_prediction: true
    use_nonlinear_obstacle_penalty: true
    visibility_cost_threshold: 2.5
    visualize_hc_graph: true
    weight_acc_lim_theta: 1
    weight_acc_lim_x: 1
    weight_acc_lim_y: 1
    weight_agent_acc_lim_theta: 2
    weight_agent_acc_lim_x: 2
    weight_agent_acc_lim_y: 2
    weight_agent_agent_safety: 2.0
    weight_agent_optimaltime: 3.0
    weight_agent_robot_rel_vel: 5.0
    weight_agent_robot_safety: 2.0
    weight_agent_robot_ttc: 1.0
    weight_agent_robot_ttcplus: 1.0
    weight_agent_robot_visibility: 5.0
    weight_agent_viapoint: 0.5
    weight_dynamic_obstacle: 50
    weight_invisible_human: 2.0
    weight_kinematics_forward_drive: 1.0
    weight_kinematics_nh: 1.0
    weight_kinematics_turning_radius: 0
    weight_max_agent_vel_theta: 2
    weight_max_agent_vel_x: 4
    weight_max_agent_vel_y: 4
    weight_max_vel_theta: 1
    weight_max_vel_x: 2
    weight_max_vel_y: 2
    weight_nominal_agent_vel_x: 2
    weight_obstacle: 50.0
    weight_optimaltime: 1.0
    weight_shortest_path: 0
    weight_viapoint: 0.05
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.1
