/**:
  ros__parameters:
    MpcLocalPlannerROS:
      footprint_model:
        type: polygon
        vertices:
        - - 0.4
          - 0.0
        - - 0.35
          - 0.35
        - - -0.2
          - 0.4
        - - -0.45
          - 0.0
        - - -0.2
          - -0.4
        - - 0.35
          - -0.35
      grid:
        type: fd_grid
        variable_grid:
          enable: false
      planning:
        objective:
          type: quadratic_form
        terminal_constraint:
          type: none
        terminal_cost:
          type: quadratic
      robot:
        type: unicycle
        unicycle:
          acc_lim_theta: 0.8
          acc_lim_x: 2.5
          acc_lim_y: 2.5
          dec_lim_x: 2.5
          max_vel_theta: 0.8
          max_vel_x: 1.1
          max_vel_x_backwards: 1.1
          max_vel_y: 0.2
      solver:
        lsq_lm:
          iterations: 10
        type: ipopt
