/**:
  ros__parameters:
    odometry_controller:
      wheels: &id001
      - drive: fl_caster_r_wheel_joint
        steer: fl_caster_rotation_joint
        steer_neutral_position: -180.0
      - drive: bl_caster_r_wheel_joint
        steer: bl_caster_rotation_joint
        steer_neutral_position: -180.0
      - drive: br_caster_r_wheel_joint
        steer: br_caster_rotation_joint
        steer_neutral_position: -180.0
      - drive: fr_caster_r_wheel_joint
        steer: fr_caster_rotation_joint
        steer_neutral_position: 0.0
    twist_controller:
      defaults:
        steer_ctrl:
          d_phi_max: 12.0
          damp: 2.25
          dd_phi_max: 40.0
          spring: 9.5
          virt_mass: 0.1
      wheels: *id001
