/**:
  ros__parameters:
    angle_resolution: 0.25
    frame_id: base_laser_front_link
    host: 141.3.80.116
    inverted: true
    scan_frequency: 25
    scan_intervals:
    - - -2.0
      - 2.0
    set_config: false
