/**:
  ros__parameters:
    joint_names:
    - fr_caster_rotation_joint
    - fl_caster_rotation_joint
    - br_caster_rotation_joint
    - bl_caster_rotation_joint
    - fr_caster_r_wheel_joint
    - fl_caster_r_wheel_joint
    - br_caster_r_wheel_joint
    - bl_caster_r_wheel_joint
    joint_state_controller:
      publish_rate: 50
      type: joint_state_controller/JointStateController
    odometry_controller:
      child_frame_id: base_footprint
      cov_pose: 0.1
      cov_twist: 0.1
      defaults:
        wheel_radius: 0.08
      frame_id: odom_combined
      publish_rate: 50
      type: cob_omni_drive_controller/OdometryController
      wheels: &id001
      - drive: fl_caster_r_wheel_joint
        steer: fl_caster_rotation_joint
        steer_neutral_position: 180.0
      - drive: bl_caster_r_wheel_joint
        steer: bl_caster_rotation_joint
        steer_neutral_position: 180.0
      - drive: br_caster_r_wheel_joint
        steer: br_caster_rotation_joint
        steer_neutral_position: 180.0
      - drive: fr_caster_r_wheel_joint
        steer: fr_caster_rotation_joint
        steer_neutral_position: 180.0
    twist_controller:
      defaults:
        steer_ctrl:
          d_phi_max: 12.0
          damp: 2.75
          dd_phi_max: 40.0
          spring: 15.0
          virt_mass: 0.1
      pub_divider: 1
      required_drive_mode: 3
      timeout: 0.5
      type: cob_omni_drive_controller/WheelController
      wheels: *id001
