/**:
  ros__parameters:
    scan_filter_chain:
    - name: range
      params:
        upper_replacement_value: 10.0
        upper_threshold: 10.0
        use_message_range_limits: false
      type: laser_filters/LaserScanRangeFilter
