/**:
  ros__parameters:
    TrajectoryPlannerROS:
      max_vel_x: $(arg speed)
      odom_topic: odom
    controller_frequency: 5.0
    controller_patience: 15.0
    controllers:
    - name: TrajectoryPlannerROS
      type: base_local_planner/TrajectoryPlannerROS
    max_planning_retries: 5.0
    planner_frequency: 5.0
    planners:
    - name: NavfnROS
      type: navfn/NavfnROS
