controllers:
  - name: TebLocalPlannerROS
    type: teb_local_planner/TebLocalPlannerROS
  - name: DwaLocalPlannerROS
    type: dwa_local_planner/DWAPlannerROS

controller_frequency: 5.0
controller_patience: 15.0
planner_frequency: 1.0

TebLocalPlannerROS:
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: false
  complete_global_plan: true
  min_obstacle_dist: 0.25
  inflation_dist: 0.6
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.5
  obstacle_poses_affected: 15
  dynamic_obstacle_inflation_dist: 0.6
  include_dynamic_obstacles: true
  costmap_converter_plugin: ''
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.1
  obstacle_cost_exponent: 4
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_shortest_path: 0
  weight_obstacle: 100
  weight_inflation: 0.2
  weight_dynamic_obstacle: 10
  weight_dynamic_obstacle_inflation: 0.2
  weight_viapoint: 1
  weight_adapt_factor: 2
  enable_homotopy_class_planning: true
  enable_multithreading: true
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_prefer_initial_plan: 0.9
  selection_obst_cost_scale: 100.0
  selection_alternative_time_cost: false
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  roadmap_graph_area_length_scale: 1.0
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  switching_blocking_period: 0.0
  viapoints_all_candidates: true
  delete_detours_backwards: true
  max_ratio_detours_duration_best_duration: 3.0
  visualize_hc_graph: false
  visualize_with_time_as_z_axis_scale: false
  shrink_horizon_backup: true
  shrink_horizon_min_duration: 10
  oscillation_recovery: true
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10
  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: true
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 5

DwaLocalPlannerROS:
  odom_topic: odom
  sim_time: 1.5
  vx_samples: 20
  controller_frequency: 5.0
  oscillation_reset_dist: 0.05
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  min_vel_trans: .1
  acc_lim_y: 2.5
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false
  vy_samples: 0
  vth_samples: 40
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_traj_pc: true
  publish_cost_grid_pc: true
