/**:
  ros__parameters:
    DwaLocalPlannerROS:
      acc_lim_y: 2.5
      controller_frequency: 5.0
      forward_point_distance: 0.325
      goal_distance_bias: 20.0
      latch_xy_goal_tolerance: false
      max_scaling_factor: 0.2
      min_vel_trans: 0.1
      occdist_scale: 0.02
      odom_topic: odom
      oscillation_reset_dist: 0.05
      path_distance_bias: 32.0
      publish_cost_grid_pc: true
      publish_traj_pc: true
      scaling_speed: 0.25
      sim_time: 1.5
      stop_time_buffer: 0.2
      vth_samples: 40
      vx_samples: 20
      vy_samples: 0
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.17
    controller_frequency: 5.0
    controller_patience: 15.0
    controllers:
    - name: DwaLocalPlannerROS
      type: dwa_local_planner/DWAPlannerROS
    planner_frequency: 1.0
