/**:
  ros__parameters:
    MpcLocalPlannerROS:
      collision_avoidance: {}
      controller:
        allow_init_with_backward_motion: true
        force_reinit_new_goal_angular: 1.57
        force_reinit_new_goal_dist: 1.0
        force_reinit_num_steps: 0
        global_plan_overwrite_orientation: true
        global_plan_prune_distance: 1.0
        max_global_plan_lookahead_dist: 1.0
        outer_ocp_iterations: 1
        prefer_x_feedback: false
        publish_ocp_results: false
        xy_goal_tolerance: 0.2
        yaw_goal_tolerance: 0.1
      grid:
        collocation_method: forward_differences
        cost_integration_method: left_sum
        dt_ref: 0.3
        grid_size_ref: 20
        variable_grid:
          enable: true
          grid_adaptation:
            dt_hyst_ratio: 0.1
            enable: true
            max_grid_size: 50
            min_grid_size: 2
          max_dt: 10.0;
          min_dt: 0.0;
        warm_start: true
        xf_fixed:
        - false
        - false
        - false
      odom_topic: odom
      planning:
        objective:
          minimum_time_via_points: {}
          quadratic_form:
            control_weights:
            - 0.1
            - 0.05
            integral_form: false
            state_weights:
            - 2.0
            - 2.0
            - 0.25
        terminal_constraint:
          l2_ball:
            radius: 5
            weight_matrix:
            - 1.0
            - 1.0
            - 1.0
        terminal_cost:
          quadratic:
            final_state_weights:
            - 10.0
            - 10.0
            - 0.5
      solver:
        ipopt:
          ipopt_numeric_options:
            tol: 1e-4
          ipopt_string_options:
            hessian_approximation: exact
            linear_solver: mumps
          iterations: 100
          max_cpu_time: -1.0
        lsq_lm:
          iterations: 100
          weight_adapt_factor_bounds: 1.5
          weight_adapt_factor_eq: 1.5
          weight_adapt_factor_ineq: 1.5
          weight_adapt_max_bounds: 500
          weight_adapt_max_eq: 500
          weight_adapt_max_ineq: 500
          weight_init_bounds: 2
          weight_init_eq: 2
          weight_init_ineq: 2
    controller_frequency: 5.0
    controller_patience: 15.0
    controllers:
    - name: MpcLocalPlannerROS
      type: mpc_local_planner/MpcLocalPlannerROS
    planner_frequency: 1.0
