/**:
  ros__parameters:
    TebLocalPlannerROS:
      complete_global_plan: true
      costmap_converter_plugin: ''
      costmap_converter_rate: 5
      costmap_converter_spin_thread: true
      costmap_obstacles_behind_robot_dist: 1.5
      delete_detours_backwards: true
      dt_hysteresis: 0.1
      dt_ref: 0.3
      dynamic_obstacle_inflation_dist: 0.6
      enable_homotopy_class_planning: true
      enable_multithreading: true
      feasibility_check_no_poses: 5
      free_goal_vel: false
      global_plan_overwrite_orientation: true
      h_signature_prescaler: 0.5
      h_signature_threshold: 0.1
      include_costmap_obstacles: true
      include_dynamic_obstacles: true
      inflation_dist: 0.6
      max_global_plan_lookahead_dist: 3.0
      max_number_classes: 4
      max_ratio_detours_duration_best_duration: 3.0
      min_obstacle_dist: 0.25
      no_inner_iterations: 5
      no_outer_iterations: 4
      obstacle_cost_exponent: 4
      obstacle_heading_threshold: 0.45
      obstacle_poses_affected: 15
      optimization_activate: true
      optimization_verbose: false
      oscillation_filter_duration: 10
      oscillation_omega_eps: 0.1
      oscillation_recovery: true
      oscillation_recovery_min_duration: 10
      oscillation_v_eps: 0.1
      penalty_epsilon: 0.1
      roadmap_graph_area_length_scale: 1.0
      roadmap_graph_area_width: 5
      roadmap_graph_no_samples: 15
      selection_alternative_time_cost: false
      selection_cost_hysteresis: 1.0
      selection_obst_cost_scale: 100.0
      selection_prefer_initial_plan: 0.9
      shrink_horizon_backup: true
      shrink_horizon_min_duration: 10
      switching_blocking_period: 0.0
      teb_autosize: true
      viapoints_all_candidates: true
      visualize_hc_graph: false
      visualize_with_time_as_z_axis_scale: false
      weight_acc_lim_theta: 1
      weight_acc_lim_x: 1
      weight_adapt_factor: 2
      weight_dynamic_obstacle: 10
      weight_dynamic_obstacle_inflation: 0.2
      weight_inflation: 0.2
      weight_kinematics_forward_drive: 1
      weight_kinematics_nh: 1000
      weight_kinematics_turning_radius: 1
      weight_max_vel_theta: 1
      weight_max_vel_x: 2
      weight_obstacle: 100
      weight_optimaltime: 1
      weight_shortest_path: 0
      weight_viapoint: 1
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.1
    controller_frequency: 5.0
    controller_patience: 15.0
    controllers:
    - name: TebLocalPlannerROS
      type: teb_local_planner/TebLocalPlannerROS
    planner_frequency: 0.0
