/**:
  ros__parameters:
    bodies:
    - color:
      - 1
      - 0.8
      - 0
      - 0.8
      footprints:
      - density: 1
        layers:
        - static
        points:
        - - -0.75
          - 0.45
        - - 0.75
          - 0.45
        - - 0.75
          - -0.45
        - - -0.75
          - -0.45
        type: polygon
      - density: 1
        layers:
        - static
        points:
        - - 0.75
          - 0.45
        - - 1.4
          - 0.45
        - - 1.4
          - 0.2
        - - 0.75
          - 0.2
        type: polygon
      - density: 1
        layers:
        - static
        points:
        - - 0.75
          - -0.2
        - - 1.4
          - -0.2
        - - 1.4
          - -0.45
        - - 0.75
          - -0.45
        type: polygon
      name: base
    - color:
      - 0.26
      - 0.3
      - 0
      - 0.3
      footprints:
      - center:
        - 0.0
        - 0.0
        collision: false
        density: 1
        layers:
        - static
        radius: 1.8
        type: circle
      name: safety_dist_circle
      pose:
      - 3
      - 0
      - 0
      type: dynamic
    plugins:
    - agent_topic: /pedsim_simulator/simulated_agents
      base_body: base
      name: vehicle_movement
      safety_dist: 1.8
      safety_dist_body: safety_dist_circle
      step_time: 0.3
      type: VehicleMovement
      update_rate: 10
      var_step_time: 0.1
